// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBFy7Bvov8WuTEFAqrY7t1Z0xcEHFihAY',
    appId: '1:340100178581:web:4babef5384ff26155a719c',
    messagingSenderId: '340100178581',
    projectId: 'graduation-forbit',
    authDomain: 'graduation-forbit.firebaseapp.com',
    storageBucket: 'graduation-forbit.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9lvMTIj0pIJsOYh-IP46P6ZDT7OCR89Y',
    appId: '1:340100178581:android:00d7a32b54d098085a719c',
    messagingSenderId: '340100178581',
    projectId: 'graduation-forbit',
    storageBucket: 'graduation-forbit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLVDb2syjAl60JccPzUSBX2a6Anflb0NA',
    appId: '1:340100178581:ios:483ee70105bd98735a719c',
    messagingSenderId: '340100178581',
    projectId: 'graduation-forbit',
    storageBucket: 'graduation-forbit.appspot.com',
    iosBundleId: 'com.example.herogamescase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLVDb2syjAl60JccPzUSBX2a6Anflb0NA',
    appId: '1:340100178581:ios:932ba9650a6035865a719c',
    messagingSenderId: '340100178581',
    projectId: 'graduation-forbit',
    storageBucket: 'graduation-forbit.appspot.com',
    iosBundleId: 'com.example.herogamescase.RunnerTests',
  );
}
